<!DOCTYPE html>
<html>
<head>
    <title>Example</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
    <h1><?=$cuong;?></h1>
    <table>
        <tr>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
        </tr>
        <tr>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
        </tr>
        <tr>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
        </tr>
        <tr>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
        </tr>
        <tr>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
        </tr>
        <tr>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
        </tr>
        <tr>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
        </tr>
        <tr>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
        </tr>
        <tr>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
            <td>STT</td>
        </tr>
    </table>
</body>
</html> 