<?php

return array(

	/*
	|--------------------------------------------------------------------------
	| Additional Compiled Classes
	|--------------------------------------------------------------------------
	|
	| Here you may specify additional classes to include in the compiled file
	| generated by the `artisan optimize` command. These should be classes
	| that are included on basically every request into the application.
	|
	*/

	'frontend/modules/delivery/models/Delivery.php',
	'frontend/modules/delivery/controllers/DeliveryController.php',
	'frontend/modules/delivery/models/Tracking.php',
	'Illuminate\Support\Facades\Response'
);
